# Generated by Django 4.2.3 on 2024-02-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_ticket_row_ticket_section_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('In progress', 'In progress'), ('Confirmed', 'Confirmed')], default='In progress', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='Amount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Mada', 'Mada')], default=None, max_length=50),
        ),
    ]
