# Generated by Django 4.2.3 on 2024-02-04 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0008_ticketrefused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketrefused',
            name='Ticket',
        ),
        migrations.AddField(
            model_name='ticketrefused',
            name='Row',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketrefused',
            name='Section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketrefused',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refused_bought_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketrefused',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='ticket_documents/'),
        ),
        migrations.AddField(
            model_name='ticketrefused',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.event'),
        ),
        migrations.AddField(
            model_name='ticketrefused',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticketrefused',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketrefused',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refused_tickets_for_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketrefused',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
