# Generated by Django 4.2.3 on 2024-02-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_remove_ticketrefused_ticket_ticketrefused_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Refused', 'Refused'), ('Accepted', 'Accepted')], default='Progress', max_length=10),
        ),
    ]
