version: "3.3"

services:
  web:
    build:
      context: "./Tick backend"
    command: gunicorn TICKETS.wsgi --bind 0.0.0.0:8000 --workers 3
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - "./Tick backend:/home/funpass/code"
      - staticfiles:/home/funpass/code/staticfiles
      # - mediafiles:/home/funpass/code/media
      - "./Tick backend/media/:/home/funpass/code/media/"
    ports:
      - "8000:8000"

  frontend:
    build: "./Ticket Frontend"
    volumes:
      - front:/app/build/

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:8081"
    volumes:
      - front:/var/www/funpass/frontend
      - staticfiles:/var/www/funpass/statics
      - mediafiles:/var/www/funpass/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - web

volumes:
  staticfiles:
  mediafiles:
  front:
  # postgres:

