# Generated by Django 4.2.3 on 2024-02-02 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.CharField(default=None, max_length=50)),
                ('Card_Name', models.CharField(default=None, max_length=50)),
                ('Card_Year', models.CharField(default=None, max_length=50)),
                ('Card_Month', models.CharField(default=None, max_length=50)),
                ('Card_CCV', models.CharField(default=None, max_length=50)),
                ('User', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
