# Generated by Django 4.2.3 on 2024-02-25 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='User',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
